live_config_reload = true

[cursor.style]
shape  = "Block"
blinking = "On"

[env]
#TERM = "xterm-256color"

[font]
size = 12.0

[scrolling]
history = 100000
multiplier = 3

[shell]
# 起動時にtmuxを起動する
program = "/usr/bin/zsh"
args=["-l", "-c", "tmux"]

[window]
dimensions = { columns = 120, lines = 32}
padding = { x = 8, y = 4}
opacity = 0.85
